# Generated by Django 2.2.18 on 2021-11-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('transport', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('logged', models.BooleanField(default=False)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('journeyid', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField(default=0)),
                ('emitted', models.IntegerField(default=0, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('transport', models.ForeignKey(default='Car', on_delete=django.db.models.deletion.CASCADE, to='api.Default')),
            ],
        ),
    ]
