# Generated by Django 3.2.9 on 2021-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='emitted',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
