# Generated by Django 3.2.9 on 2021-11-29 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
