# Generated by Django 3.2.9 on 2021-11-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scoreboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='journey',
        ),
    ]
