# Generated by Django 3.2.9 on 2021-11-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211127_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('transport', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='transport',
            field=models.ForeignKey(default='Car', on_delete=django.db.models.deletion.CASCADE, to='api.default'),
        ),
    ]
