# Generated by Django 3.2.9 on 2021-11-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211120_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='emitted',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
