# Generated by Django 3.2.9 on 2021-11-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='journeyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.journey'),
        ),
    ]
