# Generated by Django 3.2.9 on 2021-11-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_journey_emitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
