# Generated by Django 3.2.9 on 2021-11-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_journeyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='journeyid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='journey',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.journey'),
        ),
    ]
