# Generated by Django 3.2.9 on 2021-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
